version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres:14.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

  rails:
    container_name: rails
    networks:
      - default
    build:
      context: .
      dockerfile: docker-setup/production/Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - .:/backend
    environment:
      - TOKEN=$TOKEN
    env_file:
      - .env.production
    depends_on:
      - postgres

networks:
  default:
    name: backend-network
